In [1]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

In [2]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Corlu,TR,2021-02-04 14:51:56,41.1592,27.8000,59.00,77,40,8.05
1,1,Klaksvik,FO,2021-02-04 14:50:07,62.2266,-6.5890,35.60,64,40,23.02
2,2,Batagay-Alyta,RU,2021-02-04 14:51:57,67.8006,130.4114,-31.25,70,0,1.32
3,3,Ushuaia,AR,2021-02-04 14:49:41,-54.8000,-68.3000,57.20,77,75,35.68
4,4,Taga,RO,2021-02-04 14:51:57,46.9500,24.0500,55.40,54,40,25.32

In [7]:
# Get the maximum temperature.
# this is done because google maps cannot read temp less than 0 for making the heat map
#can also use list comprehension instead of the code below
#list comprehension code would be: heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp])
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))

#One caveat to using gmaps: The data we use for any mapping must be either an integer or a floating-point decimal number. Let's check the data types for the columns of our DataFrame.

city_data_df.dtypes

City_ID         int64
City           object
Country        object
Date           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
dtype: object

In [8]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [15]:

#Next, create the heatmap for the maximum temperature. The general syntax for creating a heatmap is as follows.
# 1. Assign the locations to an array of latitude and longitude pairs.
locations = city_data_df[["Lat", "Lng"]]
# 2. Assign the weights variable to some values. # get the max temp
max_temp = city_data_df["Max Temp"]
# 3. Assign the figure variable to the gmaps.figure() attribute.
#add the geographic center of Earth in the form of latitude and longitude (30.0° N and 31.0° E). Also, add a zoom level so that only one map of Earth is shown.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# 4. Assign the heatmap_layer variable to the heatmap_layer attribute and add in the locatio#assign the ns.
#assign the heat map variable                      
heat_layer = gmaps.heatmap_layer(locations, weights=temps, dissipating=False, max_intensity=300, point_radius=4)
# 5. Add the heatmap layer.
fig.add_layer(heat_layer)
#Adjust Heatmap Zoom, Intensity, and Point Radius

# 6. Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [11]:
#additional explanation about the edits below: 
#If you review the gmaps documentation, you may notice there is a dissipation option for creating heatmaps that can be added to the gmaps.heat_layer() attribute.
#The options for this are:

#The default option for the dissipation is "True," so we need to set our "dissipation" to "False."
#We can add max_intensity to make each measurement have a better gradient variance.
#We can add point_radius to make each measurement radius larger.
#Also, you'll have to tweak these values until you are satisfied with the final map.

#Let's modify our gmaps.heat_layer() attribute to heat_layer = gmaps.heatmap_layer(locations, weights=temps, dissipating=False, max_intensity=300, point_radius=4) and rerun our code.

In [16]:
#Create a Percent Humidity Heatmap
#Now that we have created our maximum temperature heatmap, let's create the heatmap for humidity. We can reuse the code and use the humidity values for the measurements.
#Add the following code to a new cell and run the cell.
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [18]:
#Create a Percent Coludiness Heatmap
locations = city_data_df[["Lat", "Lng"]]
clouds = city_data_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=clouds, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [19]:
#Create a windspeed Heatmap
#Now that we have created our maximum temperature heatmap, let's create the heatmap for humidity. We can reuse the code and use the humidity values for the measurements.
#Add the following code to a new cell and run the cell.
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
wind = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=wind, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [20]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 85

In [22]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
6,6,Hermanus,ZA,2021-02-04 14:51:57,-34.4187,19.2345,75.00,66,39,5.01
12,12,Le Port,RE,2021-02-04 14:51:59,-20.9373,55.2919,82.40,65,75,13.80
13,13,Cape Town,ZA,2021-02-04 14:51:02,-33.9258,18.4232,75.20,60,0,25.32
15,15,San Vicente,AR,2021-02-04 14:51:59,-26.6167,-54.1333,76.06,60,81,5.70
17,17,Takoradi,GH,2021-02-04 14:51:59,4.8845,-1.7554,84.13,73,17,8.95
21,21,Rikitea,PF,2021-02-04 14:52:00,-23.1203,-134.9692,77.97,69,99,11.74
22,22,Bredasdorp,ZA,2021-02-04 14:52:00,-34.5322,20.0403,75.20,50,82,10.36
26,26,Mitu,CO,2021-02-04 14:52:02,1.1983,-70.1733,77.56,89,97,2.71
29,29,Sabang,ID,2021-02-04 14:52:02,5.8933,95.3214,81.30,77,2,21.32
38,38,Avarua,CK,2021-02-04 14:48:27,-21.2078,-159.7750,77.00,88,75,2.30

In [23]:
#add the code below to see if there are any null values
preferred_cities_df.count()

City_ID       137
City          137
Country       136
Date          137
Lat           137
Lng           137
Max Temp      137
Humidity      137
Cloudiness    137
Wind Speed    137
dtype: int64

In [25]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

           City Country  Max Temp      Lat       Lng Hotel Name
6      Hermanus      ZA     75.00 -34.4187   19.2345
12      Le Port      RE     82.40 -20.9373   55.2919
13    Cape Town      ZA     75.20 -33.9258   18.4232
15  San Vicente      AR     76.06 -26.6167  -54.1333
17     Takoradi      GH     84.13   4.8845   -1.7554
21      Rikitea      PF     77.97 -23.1203 -134.9692
22   Bredasdorp      ZA     75.20 -34.5322   20.0403
26         Mitu      CO     77.56   1.1983  -70.1733
29       Sabang      ID     81.30   5.8933   95.3214
38       Avarua      CK     77.00 -21.2078 -159.7750

In [26]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

In [29]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [30]:
#If you encounter more errors, add them to the except block—like so, (IndexError, NewError)
#—and continue running your code until there are no errors
hotel_df

,City,Country,Max Temp,Lat,Lng,Hotel Name
6,Hermanus,ZA,75.00,-34.4187,19.2345,Misty Waves Boutique Hotel
12,Le Port,RE,82.40,-20.9373,55.2919,Villa Maido
13,Cape Town,ZA,75.20,-33.9258,18.4232,"Radisson Blu Hotel Waterfront, Cape Town"
15,San Vicente,AR,76.06,-26.6167,-54.1333,Complejo Turístico Farelluk
17,Takoradi,GH,84.13,4.8845,-1.7554,Raybow International Hotel
...,...,...,...,...,...,...
542,Rio Cuarto,AR,75.20,-33.1307,-64.3499,Hotel Menossi
550,Santo Domingo,DO,81.00,18.5001,-69.9886,Micro Hotel Condo Suites
552,Puerto Colombia,CO,80.60,10.9878,-74.9547,Hotel El Emigrante
554,Catuday,PH,76.50,16.2923,119.8062,GResort
558,Kutum,SD,75.69,14.2000,24.6667,Dibbo areaمنطقة دبو

In [31]:
# Add a heatmap of temperature for the vacation spots.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,
             max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [32]:
# Add a heatmap of temperature for the vacation spots and marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [35]:
#Now we can add a pop-up marker for each city that displays the hotel name, city name, country, and maximum temperature.

#From the gmaps documentation on how to add markers (Links to an external site.), we need to add an info_box_template that has the following syntax.

#info_box_template = """
#<dl>
#<dt>Name</dt><dd>{column1}</dd>
#<dt>Another name</dt><dd>{column2}</dd>
#</dl>
#"""
#This is a new code block, so let's review its form and function.

#First, the info_box_template variable is assigned to a multiline string using three quotes. The text inside the multiline string is HTML code. HTML code is defined by the opening and closing the angular brackets (e.g., <tag> and <tag/>). Angular brackets always come in pairs. The opening angular bracket is followed by some text inside, such as dl, dt, and dd. The closing angular bracket is preceded by a forward-slash ("/"). The text inside with the angular brackets is called a tag. We'll see more examples of HTML code in an upcoming module.

#Here's what these tags mean:

#The <dl> tag is a description list (dl).
#The <dt> tag is a term or name in a description list that is nested under the <dl> tag.
#The <dd> tag is used to define the term or name or <dt> tag.
#If we were to write out these tags on paper, it would look like this.

#Description List: <dl>
#Description Term: <dt>
#Description Definition: <dd>
#Description Term: <dt>
#Description Definition: <dd>
#For our purposes, we'll add the hotel name, city name, country code, and the maximum temperature values from the hotel_df DataFrame as the description definition. Our code will look like the following.
#info_box_template = """
#<dl>
#<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
#<dt>City</dt><dd>{City}</dd>
#<dt>Country</dt><dd>{Country}</dd>
#<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
#</dl>
#"""
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [36]:
# Add a heatmap of temperature for the vacation spots and marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))